import 'dotenv/config';
import { defineConfig } from 'prisma/config';
import { PrismaPg } from '@prisma/adapter-pg';
import { Pool } from 'pg';

/**
 * Prisma CLI configuration (offline-capable).
 *
 * The schema engine runs as bundled JavaScript (WASM) with the pg driver
 * adapter instead of downloading native engine binaries, so migrations,
 * db push/pull and diffs work in restricted-network environments. Prisma
 * Client itself is generated by `apps/api/scripts/prisma-generate.cjs`.
 *
 * Local databases: set DATABASE_URL (or rely on .env) and run e.g.
 *   npm run db:migrate      → prisma migrate deploy (offline-friendly)
 *   npm run db:diff         → print pending migration SQL
 */
export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  experimental: {
    adapter: true,
  },
  engine: 'js',
  adapter: async () => {
    const connectionString =
      process.env.DATABASE_URL ?? 'postgresql://postgres:postgres@127.0.0.1:5432/car_rental';
    return new PrismaPg(new Pool({ connectionString }));
  },
});
